meta_name: "Joana Bossa Jewelry"
meta_title: ""Joana Bossa Jewelry - ğ»ğ’¶ğ“ƒğ’¹ ğ’¸ğ“‡ğ’¶ğ’»ğ“‰ğ‘’ğ’¹ ğ’¿ğ‘’ğ“Œğ‘’ğ“ğ“‡ğ“ ğ“Œğ’¾ğ“‰ğ’½ ğ’¶ ğ“ˆğ“‰ğ‘œğ“‡ğ“ ğ“‰ğ‘œ ğ“‰ğ‘’ğ“ğ“"
meta_description: "Because handmade is the truest way to say â€œloveless"."
meta_image: "cover.png" # should exist in `app/assets/images/`
# twitter_account: "@your_twitter_account"   # required for Twitter Cards
